### ISSUE TITLE
1.0 - Tracking issue

### ISSUE THREAD

**Issue by banocean** [oceaann/custom#22]
# 1.0
 - [x] Moderation
   - [x] https://github.com/oceaann/custom/pull/4
   - [x] https://github.com/oceaann/custom/pull/7
   - [x] https://github.com/oceaann/custom/pull/8
 - [x] https://github.com/oceaann/custom/pull/13
 - [x] Case system
   - [x] https://github.com/oceaann/custom/pull/17
   - [x] Management commands (details, last, list, remove)
 - [ ] API + Dashboard 
   - [x] Authorization
   - [ ] Whitelist/Blacklist system
   - [x] Servers list
   - [ ] Server settings
     - [ ] Commands management 
     - [ ] Check does user have permissions to edit guild settings
     - [ ] Module/plugin enabling system
     - [x] Case settings (frontend) 
     - [ ] Automod settings (frontend) 
     - [x] Moderation settings (frontend) 
     - [ ] Saving server settings
          - [x] Cache + apply changes
          - [ ] Reload server commands
## Stabilization pr's
 - [x] https://github.com/oceaann/custom/pull/19
 - [ ] Moderation
 - [ ] Case system
